xebin - Atari XL/XE Binary File Utility
=======================================

// This file is in AsciiDoc format. It is the source for README.html.
:Compact-Option:

+xebin+ is a small command-line utility for manipulating atari binary (executable) files.
It can list contents of binary file, merge several files into a single loadable file,
or pack file in a way similar to Piotr Fusik's FlashPack.

+xebin+ is written in http://www.digitalmars.com/d/2.0/[D programming language] and tested
under Linux and, occasionally, Windows. However, it should be possible to build and run it on any
platform, for which D compiler is available.
It is designed to be easily embeddable in build scripts.


Installation
------------

Both binary releases for Windows and sources for all platforms are available at http://github.com/epi/xebin[github].

To build +xebin+ from sources, you need http://www.digitalmars.com/d/download.html[DMD 2.076] or newer.

Go to console window, and type:

--------------
$ dub build -b release
--------------

After successful build, you can move file +xebin.exe+ or +xebin+ to a directory within your +PATH+.


Usage
-----

A general syntax is:

----------------------------
$ xebin command [options] [input_files]
----------------------------

You can place options wherever you wish in the command line, as well as join
single-letter options together, if they do not require parameters.

For all specific commands below you can skip input files specification.
In such case, +xebin+ will read from standard input.

Similarly, +xebin+ writes its output to standard output, but you can (and usually
you should) specify an output file name with +-o+ or +--output+ option.
When using +-v+ or +--verbose+ option, additional output is always written to
+stdout+.

You can see the list of available commands and options by typing:

----------------------------
$ xebin help
----------------------------

Listing binary file contents
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

----------------------------
$ xebin l[ist] [input_files]
----------------------------

Example output:

-------------------------------------
D:\proj\tipview>xebin l tv10.xex
  0. 8C00-903C (043D)
  1. 91DD-A3B7 (11DB)
  2. 02E0-02E1 (0002)  ; RUN $91FD
-------------------------------------

With +-v+ contents of packed blocks are shown, e.g.:

-------------------------------------
D:\proj\fail\vrgb\xebin l vrgb10.xex
  0. 4000-470E (070F) (FlashPack 1.0)
      0. 3000-39A0 (09A1)
      1. 3C21-3C48 (0028)
      2. 3CC1-3CF1 (0031)
      3. 02E0-02E1 (0002)  ; RUN $3000
  1. 02E2-02E3 (0002)  ; INIT $4000
-------------------------------------

Merging two or more files
~~~~~~~~~~~~~~~~~~~~~~~~~

----------------------------
$ xebin m[erge] [-o=fn] [-v] [input_files]
----------------------------

Blocks from all files are concatenated in the order they appear in the list
of input files.

Reduntant +FFFF+ headers are dropped.

+-v+ displays layout of resulting file.

Extracting block from binary file
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

----------------------------
$ xebin e[xtract] [-n=pos] [-r] [-o=fn] [-v] [input_files]
----------------------------

Default option is to extract first block of first input file, including its binary header.

Option +-n=pos+ or +--position=pos+ allows extracting other blocks.
Block numbering is continuous across all input files and starts from 0.
Only one block is extracted at a time.

Option +-r+ or +--raw+ strips header from extracted block.

+-v+ displays info about extracted block.

Disassembling binary file
~~~~~~~~~~~~~~~~~~~~~~~~~

----------------------------
$ xebin d[isasm] [-o=fn] [input_files]
----------------------------

Each block is disassembled as code, preceded by an +ORG+ directive with its load
address. Blocks setting +RUNAD+ or +INITAD+ are emitted as +DTA A()+ with the address
they point to.

Labels are created for all addresses referenced by the disassembled code, including the
run and init addresses. Addresses outside the loaded blocks are defined with +EQU+ at
the beginning of the output, and a reference pointing into the middle of an instruction
is printed as an offset from that instruction's label, e.g. +L2103+1+.

Opcode names and argument syntax are taken from http://atari800.sourceforge.net/[Atari 800]
emulator. Bytes that do not decode into an official 6502 instruction, as well as an
instruction truncated by the end of a block, are emitted as +DTA+, so that the whole
output can be fed back to http://atariarea.krap.pl/x-asm/[xasm] and assembled into
the original file.

Example output:

-------------------------------------
$ xebin d example.xex
L0014	EQU $0014
L02C8	EQU $02C8
	ORG $2000
L2000	LDA #$0F
	STA L02C8
L2005	LDA L0014
	CMP L0014
	BEQ L2005
	JMP L2000
	ORG $02E0
	DTA A(L2000)
-------------------------------------

When more than one input file is given, disassembly of each of them is preceded by
a comment with the file name.

Running binary file
~~~~~~~~~~~~~~~~~~~

----------------------------
$ xebin r[un] [--trace=what] [input_file]
----------------------------

The file is loaded into memory of a simple built-in emulator and run: each +INIT+
routine is called as soon as the block setting it is loaded, and the +RUN+ routine
is called once the whole file is loaded. Only the first input file is used.

Only the CPU (NMOS 6502) and a few OS entry points are emulated. There is neither OS
ROM nor any hardware, so this is useful for programs that compute and do character
I/O, and not for anything that touches ANTIC, POKEY or GTIA.

+CIOV+ ($E456) is served by the host:

- IOCB #0 is the console: get record reads a line from +stdin+, put record and put
characters write to +stdout+, and +$9B+ is translated to a newline.
- IOCB #1 to #7 support open, get, put and close on +D:+ files, which are mapped to
files in the current directory (+>+ in an Atari file name becomes +/+).
Other devices are rejected with error 130.

Commands other than the above return error 132, just like CIO would.

The emulator stops when the +RUN+ routine returns (or the last +INIT+ routine, if the
file has no +RUN+ block), as well as when the program jumps through +DOSVEC+.
A +BRK+ stops it with an error message pointing at the offending address.

Nothing is traced by default. +--trace=what+ takes a comma-separated list of traces
to enable, and may be given more than once, each occurrence adding to the set of
enabled traces, so that +--trace=load,cio+ and +--trace=load --trace=cio+ mean the
same. +--trace=all+ enables every trace. All traces go to +stderr+, so they can be
told apart from the output of the program itself.

+load+ reports each block as it is loaded, along with the init and run addresses
taken from the file:

-------------------------------------
$ xebin r --trace=load hello.xex
Load 51 bytes at 2000-2032
Load 2 bytes at 02E0-02E1
Run at 2000
Hello!
-------------------------------------

+cio+ reports every CIO call, with the parameters taken from the IOCB:

-------------------------------------
$ xebin r --trace=cio hello.xex
CIO #00 cmd=0b addr=0700 len=0007 aux1=00 aux2=00
Hello!
-------------------------------------

+cpu+ reports, for each executed instruction, the registers and flags as they were
before it, its disassembly, and the memory reads and writes it makes:

-------------------------------------
$ xebin r --trace=cpu hello.xex
A=00 X=00 Y=00 S=FD P=--*-----  2000  A2 00      LDX #$00
A=00 X=00 Y=00 S=FD P=--*---Z-  2002  BD 2C 20   LDA $202C,X    R 202C 48
A=48 X=00 Y=00 S=FD P=--*-----  2005  F0 06      BEQ $200D
A=48 X=00 Y=00 S=FD P=--*-----  2007  9D 00 07   STA $0700,X    W 0700 48
-------------------------------------

Compressing binary file
~~~~~~~~~~~~~~~~~~~~~~~

----------------------------
$ xebin p[ack] [-a=ad] [-s] [-o=fn] [-v] [input_files]
----------------------------

The command compresses a binary file using FlashPack algorithm. For each group of
blocks between blocks that write +RUNAD+ or +INITAD+, it creates a single packed
block with its own depacker. Blocks that write those vectors are copied unchanged,
so that the loader still runs them at the point the original file expected.

+xebin+ tries to determine address of packed block so it won't collide with
unpacked blocks. You can override its guess, or just give it a hand when it fails
to do so, by using +-a=ad+ or +--address=ad+ option. Address may be supplied
in decimal or hexadecimal (with +0x+ or +$+ prefix) notation. Address prefixed
with +-+ is treated as address of the last byte of packed block.

+-s+ or +--disable-os+ will cause the interrupts and OS ROM be disabled during depacking.
Apart from an unnoticeable speed-up, it allows for placing unpacked blocks in areas
of RAM normally hidden under OS ROM.

+-v+ displays layout of resulting file and some statistics.

Unpacking binary file
~~~~~~~~~~~~~~~~~~~~~

+xebin+ can also unpack FlashPack-compressed files. It handles files created by
Piotr Fusik's FlashPack 1.0 or 2.1, or +xebin+ itself.

----------------------------
$ xebin u[npack] [-o=fn] [-v] [input_files]
----------------------------

+-v+ displays layout of resulting file.


History
-------

unreleased::

Added +run+ command, which loads and executes a binary file in a built-in emulator,
with OS calls served by the host.
The emulator implements all 65x02 variants (NMOS 6502, 65C02, Rockwell R65C02 and W65C02S)
with cycle-exact timing; the +run+ command uses the NMOS 6502.
Added +--trace+ option, which reports what the +run+ command loads, executes
and asks CIO for.
Disassembler now creates labels for addresses referenced inside the disassembled code.
Disassembler output is now directly assemblable with xasm.
+INIT+ and +RUN+ are now correctly detected for every block that overwrites them.
Fixed reading from non-seekable input files, such as pipes.
Fixed crash when packing blocks shorter than two bytes.
Build process switched to dub, with xasm used as a separate dependency package.

xebin 1.1.0 (2011-04-20)::

Fixed bug in auto address setting for packed data.
Command line options and parameters work according to description.
Added support for hexadecimal addresses.
Added simple disassembler.
Added option to extract block from binary file.
Added option to list contents of compressed blocks.
+xebin pack -v+ shows some statistics.
Build process simplified by incorporating xasm in xebin.

xebin 1.0.0 (2011-01-13)::

Initial release.


Bugs
----

It is impossible to set different addresses for multiple input files in pack option,
as well as different settings for OS ROM and interrupts.


Feedback
--------

Issues with +xebin+ should be reported via http://github.com/epi/xebin/issues[this tracker].


Authors
-------

Piotr Fusik::
Original FlashPack program, depacker routines, testing.

Adrian Matoga::
Programming.


License
-------

------------------------------------
Poetic License:

This work 'as-is' we provide.
No warranty express or implied.
We've done our best,
to debug and test.
Liability for damages denied.

Permission is granted hereby,
to copy, share, and modify.
Use as is fit,
free or for profit.
These rights, on this notice, rely.
------------------------------------
